version: '2'

services:
  postgres:
    container_name: maestro_postgres
    image: postgres:11.0
    environment:
      POSTGRES_DB: 'maestro_dev'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGPORT: 5432
    ports:
      - '15432:5432'


